### ISSUE TITLE
Glue/hadoop-2.2.0 and Pig

### ISSUE THREAD

**Issue by techiesavy** [gerritjvv/glue#67] opened 2014-03-06 20:32 UTC
hi,

Have installed new glue-rest rpm. There is none of the jars available in /opt/glue/lib-pig directory. Which jars are to be configured. I have configure as,

classpath = ['/opt/glue/lib', '/opt/glue/conf', '/opt/hadoop', '/opt/hadoop/conf', '/opt/glue/lib-pig']

I have copied the pig_withouthadoop-0.12.1.jar to glue pig-lib folder. Otherwise getting classnotfound error. 

Also in pig-0.12(downloaded from apache) there are different jars, do I need to keep as it is?

getting the below error when try to run,

2014-03-06 15:23:25,471 [main] ERROR org.apache.pig.PigServer - exception during parsing: Error during parsing. Unable to check name hdfs://master:9005/user/root
Failed to parse: Pig script failed to parse: 
<file mytest.pig, line 14, column 6> pig script failed to validate: org.apache.pig.backend.datastorage.DataStorageException: ERROR 6007: Unable to check name hdfs://master:9000/user/root
	at org.apache.pig.parser.QueryParserDriver.parse(QueryParserDriver.java:196)
Caused by: java.io.IOException: Failed on local exception: java.io.EOFException; Host Details : local host is: "master/127.0.0.1"; destination host is: "master":9005;

**Comment by pks22** [comment] 2016-03-28 05:24
Hello, 

I am getting the same issue. I am trying to run Pig from Java code. I have used Pig server. It is NOT multi- threaded or anything.

Here is the exception that I am getting:
org.apache.pig.impl.logicalLayer.FrontendException: ERROR 1000: Error during parsing. Unable to check name hdfs://Namenode:8020/user/test
	at org.apache.pig.PigServer$Graph.parseQuery(PigServer.java:1748)
	at org.apache.pig.PigServer$Graph.registerQuery(PigServer.java:1682)
	at org.apache.pig.PigServer.registerQuery(PigServer.java:623)
	at org.apache.pig.PigServer.registerQuery(PigServer.java:636)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: Failed to parse: Pig script failed to parse: 
<line 1, column 4> pig script failed to validate: org.apache.pig.backend.datastorage.DataStorageException: ERROR 6007: Unable to check name hdfs://Namenode:8020/user/test
	at org.apache.pig.parser.QueryParserDriver.parse(QueryParserDriver.java:199)
	at org.apache.pig.PigServer$Graph.parseQuery(PigServer.java:1735)
	... 10 more
Caused by: 
<line 1, column 4> pig script failed to validate: org.apache.pig.backend.datastorage.DataStorageException: ERROR 6007: Unable to check name hdfs://Namenode:8020/user/test

Thank you

**Comment by gerritjvv** [comment] 2016-03-28 16:30
hi, please send me the version of hadoop+pig you're using and also the workflow you have (if you don't want to paste/attach it here, just ping to my email at gerritjvv@gmail.com).

**Comment by gerritjvv** [comment] 2016-03-28 16:34
more than being a glue issue this is a pig and hadoop issue. Most of the posts about his issue e.g http://stackoverflow.com/questions/19330860/apache-pig-error-6007-unable-to-check-name-message out there suggest that you are not using the same version of pig+hadoop as you have on your cluster. Please verify that you only have the jars on your class path for the version of hadoop  you have.

**Comment by pks22** [comment] 2016-03-28 17:15
Hi,

Sent out an enivte in google hangouts. Pl accept it

On Mon, Mar 28, 2016 at 9:34 AM, Gerrit <notifications@github.com> wrote:

> more than being a glue issue this is a pig and hadoop issue. Most of the
> posts about his issue e.g
> http://stackoverflow.com/questions/19330860/apache-pig-error-6007-unable-to-check-name-message
> out there suggest that you are not using the same version of pig+hadoop as
> you have on your cluster. Please verify that you only have the jars on your
> class path for the version of hadoop you have.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/gerritjvv/glue/issues/67#issuecomment-202474347>
>



-- 
Thank you,
Pranay

**Comment by gerritjvv** [comment] 2016-03-29 20:45
Marking as closed for the moment, please reopen if you still see any of these issues.

**Closed by gerritjvv** 2016-03-29 20:45 UTC
